# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SEAMS Workshop
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The Software Engineering for Applied Mathematical Sciences (SEAMS) Workshop site.
  The site provides workshop logistics information (application information, dates, locations, etc)
  as well as covering the workshop material.
baseurl: "" # the subpath of your site, e.g. /blog
url: "/" # the base hostname & protocol for your site
twitter_username: SeamsWorkshop
github_username:  jekyll

# Build settings
markdown: kramdown
exclude: ["README.md", "run.sh"]

# Collections
collections:
  warmup:
    output: true
    permalink: /:collection/:slug:output_ext

defaults:
  -
    scope:
      path: ""
      type: warmup
    values:
      layout: page
