# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SEAMS Workshop v4
longtitle: SEAMS Workshop v4 ~ 26 Nov - 7 Dec ~ Muizenberg, Cape Town, RSA
email: seams@aims.ac.za
description: > # this means to ignore newlines until "baseurl:"
  The Software Engineering for Applied Mathematical Sciences (SEAMS) Workshop site,
  covering logistics and materials.
baseurl: "" # the subpath of your site, e.g. /blog
url: "/" # the base hostname & protocol for your site
twitter_username: SeamsWorkshop
gitlab_username:  SEAMS-Workshop

# Build settings
markdown: kramdown
exclude: ["README.md", "Makefile", "*.json", "*.mk"]

taking_apps: 
  url: https://goo.gl/forms/nXALwJ7Fn4BUt0lR2
  end: 'August 31st (Friday), 2018'

# Collections
collections:
  warmup:
    output: true
    permalink: /:collection/:slug:output_ext
  topic:
    output: true
    permalink: /:collection/:slug/
  session:
    output: true
    permalink: /:collection/:slug:output_ext
  practical:
    output: true
    permalink: /:collection/:slug:output_ext
  project:
    output: true
    permalink: /:collection/:slug:output_ext
  faculty:
    output: false


defaults:
  -
    scope:
      path: ""
      type: warmup
    values:
      layout: page
  -
    scope:
      path: ""
      type: topic
    values:
      layout: page
  -
    scope:
      path: ""
      type: session
    values:
      layout: page
  -
    scope:
      path: ""
      type: practical
    values:
      layout: page
  -
    scope:
      path: ""
      type: project
    values:
      layout: page
